### ISSUE TITLE
Release Checklist

### ISSUE THREAD

**Issue by in0rdr** [in0rdr/diary#66]
- [ ] prepare changelog tags and CHANGELOG file
- [ ] remove unstable from DIARY_VERSION
- [ ] commit and add tag
- [ ] bump DIARY_VERSION and add -unstable, commit
